# Generated by Django 2.2.5 on 2019-10-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myphone', models.CharField(max_length=10)),
                ('myname', models.CharField(max_length=100)),
                ('myemail', models.CharField(max_length=100)),
                ('mypassword', models.CharField(max_length=100)),
                ('myre_password', models.CharField(max_length=100)),
            ],
        ),
    ]
