# Generated by Django 2.2.5 on 2019-10-12 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='water',
            old_name='myemail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='water',
            old_name='myname',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='water',
            old_name='mypassword',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='water',
            name='myphone',
        ),
        migrations.RemoveField(
            model_name='water',
            name='myre_password',
        ),
    ]
